name: Release

on:
  push:
    branches:
      - "main"

permissions:
    contents: write
    packages: write


jobs:
  get-next-version:
    name: Get next version
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      hasNextVersion: ${{ steps.get-next-version.outputs.hasNextVersion }}
      version: ${{ steps.get-next-version.outputs.version }}

    steps:
      - name: Clone repository
        uses: actions/checkout@v6
        with:
          fetch-depth: "0"
      - name: Get next version
        id: get-next-version
        uses: thenativeweb/get-next-version@2.7.1

  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: get-next-version

    if: needs.get-next-version.outputs.hasNextVersion == 'true'

    steps:
      - name: Clone repository
        uses: actions/checkout@v6
        with:
          fetch-depth: "0"
      - name: Use Go
        uses: actions/setup-go@v6
        with:
          go-version-file: ./go.mod
      - name: Create new version
        run: |
          git tag v${{ needs.get-next-version.outputs.version }}
          git push origin v${{ needs.get-next-version.outputs.version }}
      - name: Build artifacts
        run: |
          make build BUILD_VERSION=v${{ needs.get-next-version.outputs.version }}
      - name: Release new version
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/*"
          tag: v${{ needs.get-next-version.outputs.version }}
          generateReleaseNotes: true

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          provenance: mode=max
          push: true
          tags: |
            ghcr.io/matthiasharzer/hka-2fa-proxy:latest
            ghcr.io/matthiasharzer/hka-2fa-proxy:${{ needs.get-next-version.outputs.version }}
          build-args: |
            version=v${{ needs.get-next-version.outputs.version }}
